module.exports = { "2step" : { "dance" : true, "electronic" : ["2step"] },
  "80's disco" : { "electronic" : ["80s", "disco"], "dance" : true },
  "90s" : null,
  "abstract" : { "classical" : ["abstract"] },
  "acid" : { "dance" : true, "electronic" : ["acid"] },
  "acid house" : { "dance" : true, "electronic" : ["acid", "house" ] },
  "acidtechno" : { "dance" : true, "electronic" : ["acid", "techno" ] },
  "afro" : { "dance" : true, "international" : ["afro"] },
  "afro beat" : { "dance" : true, "international" : ["afro"] },
  "afro house" : { "dance" : true, "electronic" : ["house"], "international" : ["afro"] },
  "afrobeat" : { "dance" : true, "international" : ["afro"] },
  "afrocuban" : { "dance" : true, "international" : ["afro", "cuban"] },
  "allround" : null,
  "alt" : { "alternative" : true },
  "ambient" : { "new age" : ["ambient"], "instrumental" : true },
  "artist" : null,
  "avant garde" : { "classical" : ["avant garde"] },
  "avant-garde metal" : { "classical" : ["avant garde"], "rock" : ["metal"] },
  "ballroom" : { "dance" : ["ballroom"] },
  "bass" : { "dance" : ["bass"] },
  "beach house" : { "dance" : ["beach"], "electronic" : ["house"] },
  "berghain" : { "international" : ["berghain"] },
  "berlin" : { "international" : ["berlin"] },
  "bigroom house music" : { "dance" : true, "electronic" : ["house"] },
  "blues" : { "blues" : true },
  "blues rock" : { "blues" : true, "rock" : true },
  "boogie" : { "dance" : true, "hip-hop" : ["boogie"] },
  "booty-shakin' house" : { "electronic" : ["house"] },
  "bossa" : { "latin" : true, "international" : ["bossa"] },
  "breakbeat" : { "dance" : true, "hip-hop" : ["breakbeat"] },
  "breakcore" : { "dance" : true, "electronic" : ["breakcore"] },
  "breaks" : { "dance" : true, "hip-hop" : ["breaks"] },
  "bugged out" : { "dance" : true, "electronic" : ["bugged out"] },
  "chicago" : { "country" : true, "jazz" : ["chicago"] },
  "chicago house" : { "jazz" : ["chicago"], "electronic" : ["house"] },
  "chill out" : null,
  "chillout" : null,
  "christian rap" : { "religious" : ["christian"], "hip-hop" : ["rap"] },
  "circus" : null,
  "classic" : { "classical" : true },
  "classic balearic sound" : null,
  "classic house" : { "dance" : true, "electronic" : ["house"] },
  "classic rock" : { "classical" : true, "rock" : true },
  "classical" : { "classical" : true },
  "classics" : { "classical" : true },
  "club" : { "dance" : true },
  "cool" : null,
  "cosmic" : null,
  "country" : { "country" : true },
  "culture" : null,
  "cyberfunk" : { "electronic" : true, "R&B" : ["funk"] },
  "dance" : { "dance" : true },
  "dance music" : { "dance" : true },
  "dance music." : { "dance" : true },
  "dance/electro" : { "dance" : true },
  "dancehall" : { "dance" : true },
  "dark" : null,
  "dark disco" : { "pop" : ["disco"] },
  "deep" : { "dance" : true,  "electronic" : ["deep"] },
  "deep affair" : { "dance" : true,  "electronic" : ["deep"] },
  "deep detroit techno" : { "dance" : true,  "electronic" : ["deep", "techno"] },
  "deep electronic music" : { "dance" : true,  "electronic" : ["deep"] },
  "deep electronics" : { "dance" : true,  "electronic" : ["deep"] },
  "deep groove" : { "dance" : true,  "electronic" : ["deep"] },
  "deep house" : { "dance" : true,  "electronic" : ["deep", "house"] },
  "deep house & techno" : { "dance" : true,  "electronic" : ["deep", "house", "techno"] },
  "deep house/ soul" : { "dance" : true,  "electronic" : ["deep", "house"], "R&B" : ["soul"] },
  "deep melodic house" : { "dance" : true,  "electronic" : ["deep", "melodic", "house"] },
  "deep tech" : { "dance" : true,  "electronic" : ["deep", "techno"] },
  "deep tech house" : { "dance" : true,  "electronic" : ["deep", "techno", "house"] },
  "deep techno" : { "dance" : true,  "electronic" : ["deep", "techno"] },
  "deep-house" : { "dance" : true,  "electronic" : ["deep", "house"] },
  "deephouse" : { "dance" : true,  "electronic" : ["deep", "house"] },
  "deephuse" : { "dance" : true,  "electronic" : ["deep", "house"] },
  "detroit" : null,
  "detroit real techno" : { "dance" : true,  "electronic" : ["techno"] },
  "detroit techno" : { "dance" : true,  "electronic" : ["techno"] },
  "dirty house" : { "dance" : true,  "electronic" : ["house"] },
  "disco" : { "dance" : true, "pop" : ["disco"] },
  "disco (old)" : { "dance" : true, "pop" : ["disco"] },
  "disco house" : { "dance" : true, "pop" : ["disco"], "electronic" : ["house"] },
  "dj" : null,
  "dj tools" : null,
  "dnb" : { "dance" : ["drum & bass"] },
  "downtempo" : { "dance" : true },
  "dreamy electronic dance music" : { "dance" : true, "electronic" : true },
  "drone metal" : { "rock" : ["metal"] },
  "drum" : { "dance" : ["drum & bass"] },
  "drum & bass" : { "dance" : ["drum & bass"] },
  "drum 'n bass" : { "dance" : ["drum & bass"] },
  "dub" : { "dance" : true, "electronic" : ["dubstep"] },
  "dub techno" : { "dance" : true, "electronic" : ["dubstep", "techno"] },
  "dubby" : { "dance" : true, "electronic" : ["dubstep"] },
  "dubstep" : { "dance" : true, "electronic" : ["dubstep"] },
  "dubtechno" : { "dance" : true, "electronic" : ["dubstep", "techno"] },
  "early hardcore" : { "dance" : true, "electronic" : ["hardcore"] },
  "eclectic" : null,
  "eclectico" : null,
  "edm" : { "dance" : true, "electronic" : true },
  "efunk" : { "dance" : true, "electronic" : true },
  "elecronic music" : { "dance" : true, "electronic" : true },
  "electonic" : { "dance" : true, "electronic" : true },
  "electornic" : { "dance" : true, "electronic" : true },
  "electric" : { "dance" : true, "electronic" : true },
  "electro" : { "dance" : true, "electronic" : true },
  "electro house" : { "dance" : true, "electronic" : ["house"] },
  "electroclash" : { "dance" : true, "electronic" : true },
  "electronic" : { "dance" : true, "electronic" : true },
  "electronic club music" : { "dance" : true, "electronic" : true },
  "electronic dance" : { "dance" : true, "electronic" : true },
  "electronic dance music" : { "dance" : true, "electronic" : true },
  "electronic music" : { "dance" : true, "electronic" : true },
  "electronic music with attitude" : { "dance" : true, "electronic" : true },
  "electronic muzak" : { "dance" : true, "electronic" : true },
  "electronica" : { "dance" : true, "electronic" : true },
  "electronical music" : { "dance" : true, "electronic" : true },
  "electronics" : { "dance" : true, "electronic" : true },
  "electronique" : { "dance" : true, "electronic" : true },
  "eletro house" : { "dance" : true, "electronic" : ["house"] },
  "eletronica" : { "dance" : true, "electronic" : true },
  "ethnic" : null,
  "eurodance" : { "dance" : true, "electronic" : true },
  "experimental" : null,
  "experimental rock" : { "rock" : true },
  "film score" : null,
  "folk" : { "country" : ["folk"] },
  "funk" : { "dance" : true, "R&B" : ["funk"] },
  "funky" : { "dance" : true, "R&B" : ["funk"] },
  "funky house" : { "dance" : true, "electronic" : ["house"] },
  "future beats" : { "dance" : true, "electronic" : ["house"] },
  "future funk" : { "dance" : true, "R&B" : ["funk"] },
  "future house" : { "dance" : true, "electronic" : ["house"] },
  "future jazz" : { "dance" : true, "jazz" : true },
  "future old school" : null,
  "garage" : { "rock" : ["garage"] },
  "generation bass" : null,
  "glitch" : { "dance" : true, "hip-hop" : ["glitch"] },
  "glitch hop" : { "dance" : true, "hip-hop" : ["glitch"] },
  "goa" : null,
  "good vibes & tings" : null,
  "gospel" : { "religious" : ["christian"] },
  "groove" : { "dance" : true },
  "grove" : { "dance" : true },
  "happy hardcore" : { "dance" : true, "electronic" : ["hardcore"] },
  "hard dance" : { "dance" : ["hard"] },
  "hard edm" : { "dance" : ["hard"], "electronic" : true },
  "hard house" : { "dance" : ["hard"], "electronic" : ["house"] },
  "hard rock" : { "dance" : ["hard"], "rock" : true },
  "hard techno" : { "dance" : ["hard"], "electronic" : ["techno"] },
  "hardcore" : { "dance" : true, "electronic" : ["hardcore"] },
  "hardrock" : { "rock" : ["hard rock"] },
  "hardstyle" : { "dance" : true, "electronic" : ["hardstyle"] },
  "hardsyle" : { "dance" : true, "electronic" : ["hardstyle"] },
  "hardsytle" : { "dance" : true, "electronic" : ["hardstyle"] },
  "hardtechno" : { "dance" : ["hard"], "electronic" : ["techno"] },
  "hardtrap" : { "dance" : ["hard"], "electronic" : ["trap"] },
  "heavy bass music" : { "dance" : true },
  "hi-tech soul" : { "dance" : true, "blues" : ["soul"] },
  "high quality dance music" : { "dance" : true },
  "high-tech minimal" : { "dance" : true },
  "hip hip" : { "dance" : true, "hip-hop" : true },
  "hip hop" : { "dance" : true, "hip-hop" : true },
  "hip-hop" : { "dance" : true, "hip-hop" : true },
  "hiphop" : { "dance" : true, "hip-hop" : true },
  "horror punk" : { "rock" : ["punk"] },
  "house" : { "dance" : true, "electronic" : ["house"] },
  "house music" : { "dance" : true, "electronic" : ["house"] },
  "house techno" : { "dance" : true, "electronic" : ["house", "techno"] },
  "house. techno" : { "dance" : true, "electronic" : ["house", "techno"] },
  "hunch music" : { "dance" : true, "electronic" : true },
  "improvisation" : null,
  "indie" : { "indie" : true },
  "indie dance" : { "indie" : true, "dance" : true },
  "indie house" : { "indie" : true, "dance" : true, "electronic" : ["house"] },
  "industrial techno" : { "indie" : true, "dance" : true, "electronic" : ["techno"] },
  "inspirational" : { "religious" : true },
  "instrumental psychedelic music" : { "instrumental" : true, "electronic" : ["psychedelic"] },
  "intelligent house music" : { "electronic" : ["house"] },
  "jack" : { "dance" : true },
  "jackin" : { "dance" : true },
  "jackin and tech-house" : { "dance" : true, "electronic" : ["techno", "house"] },
  "jam band" : { "rock" : true },
  "jazz" : { "jazz" : true },
  "jazz influence" : { "jazz" : true },
  "jazzy" : { "jazz" : true },
  "jazzy hip hop" : { "jazz" : true, "hip-hop" : true },
  "jersey club" : null,
  "jungle" : null,
  "latin" : { "latin" : true },
  "latin and funk" : { "latin" : true, "R&B" : ["funk"] },
  "latin house" : { "latin" : true, "electronic" : ["house"] },
  "liquid drum & bass" : { "dance" : ["drum & bass"] },
  "live act" : null,
  "lounge" : null,
  "lounge-radio" : null,
  "low slung" : { "dance" : true, "electronic" : true },
  "mad desert" : { "dance" : true },
  "mango" : { "dance" : true },
  "mantzur style" : { "dance" : true },
  "masculino" : { "dance" : true },
  "mature" : { "dance" : true },
  "melodic house" : { "dance" : true, "electronic" : ["house", "melodic"] },
  "melodic progressive house" : { "dance" : true, "electronic" : ["house", "melodic", "progressive"] },
  "melodic tech-house" : { "dance" : true, "electronic" : ["house", "melodic", "techno"] },
  "melodic techno" : { "dance" : true, "electronic" : ["techno", "melodic"] },
  "metal" : { "rock" : ["metal"] },
  "miniamal" : { "indie" : ["minimal"] },
  "minima" : { "indie" : ["minimal"] },
  "minimal" : { "indie" : ["minimal"] },
  "minimal highlife" : { "indie" : ["minimal"] },
  "minimal house" : { "indie" : ["minimal"], "electronic" : ["house"] },
  "minimal techno" : { "indie" : ["minimal"], "electronic" : ["techno"] },
  "mish mash" : null,
  "modern-funk" : { "dance" : true, "R&B" : ["funk"] },
  "moombahton" : null,
  "mysterious" : null,
  "märchentechno" : { "electronic" : ["techno"] },
  "neo-brass band" : { "rock" : true },
  "neosoul" : { "R&B" : ["soul"] },
  "new wave" : { "rock" : ["new wave"] },
  "noise" : null,
  "noise rock" : { "rock" : true },
  "nu disco" : { "pop" : ["disco"], "dance" : true, "electronic" : true },
  "nu-disco" : { "pop" : ["disco"], "dance" : true, "electronic" : true },
  "nu-groove" : { "pop" : ["disco"], "dance" : true, "jazz" : true },
  "nu-jazz" : { "pop" : ["disco"], "dance" : true, "jazz" : true },
  "oldschool" : { "dance" : true, "hip-hop" : ["old school"] },
  "organic house" : { "dance" : true, "electronic" : ["house"] },
  "perlon" : { "dance" : true, "electronic" : ["techno", "house"] },
  "pieces of e-sci-fi music" : null,
  "pop" : { "pop" : true },
  "pop rock" : { "pop" : true, "rock" : true },
  "post punk" : { "rock" : ["punk", "post rock"] },
  "post punk industrial" : { "rock" : ["punk", "industrial", "post rock"] },
  "post rock" : { "rock" : ["post rock"] },
  "power jazz" : { "jazz" : ["power"] },
  "powerhouse" : null,
  "producer" : null,
  "progesive" : { "dance" : true, "electronic" : ["progressive"] },
  "progressive" : { "dance" : true, "electronic" : ["progressive"] },
  "progressive house" : { "dance" : true, "electronic" : ["progressive", "house"] },
  "progressive house. electro" : { "dance" : true, "electronic" : ["progressive", "house"] },
  "progressive trance" : { "dance" : true, "electronic" : ["progressive", "trance"] },
  "psy" : { "dance" : true, "electronic" : ["psychedelic"] },
  "psy trance" : { "dance" : true, "electronic" : ["psychedelic", "trance"] },
  "psy-trance" : { "dance" : true, "electronic" : ["psychedelic", "trance"] },
  "psychedelic" : { "dance" : true, "electronic" : ["psychedelic"] },
  "psychedelic experimental electronic" : { "dance" : true, "electronic" : ["psychedelic"] },
  "psychedelic rock" : { "dance" : true, "electronic" : ["psychedelic"], "rock" : true },
  "psychédélique" : { "dance" : true, "electronic" : ["psychedelic"] },
  "psyprog" : { "dance" : true, "electronic" : ["psychedelic", "progressive"] },
  "psytrance" : { "dance" : true, "electronic" : ["psychedelic", "trance"] },
  "punk" : { "rock" : ["punk"] },
  "quality house" : { "dance" : true, "electronic" : ["house"] },
  "r & b" : { "R&B" : true },
  "r& b" : { "R&B" : true },
  "r&b" : { "R&B" : true },
  "r&bsoul" : { "R&B" : ["soul"] },
  "rap" : { "hip-hop" : ["rap"] },
  "raw hardstyle" : { "dance" : true, "electronic" : ["hardstyle"] },
  "reggae" : { "reggae" : true },
  "rock" : { "rock" : true },
  "samba" : { "dance" : true, "latin" : true },
  "schranz" : null,
  "sexy" : { "dance" : true },
  "shaman cowboy techno" : { "dance" : true },
  "shuffled beats" : { "dance" : true },
  "sludge metal" : { "rock" : ["metal"] },
  "soft" : { "instrumental" : true },
  "sophisticated electronica music" : { "dance" : true, "electronic" : true },
  "soul" : { "dance" : true, "R&B" : ["soul"] },
  "soul house" : { "dance" : true, "electronic" : ["house"], "R&B" : ["soul"] },
  "soul music" : { "dance" : true, "R&B" : ["soul"] },
  "soulful" : { "dance" : true, "R&B" : ["soul"] },
  "soulful acoustic" : { "dance" : true, "R&B" : ["soul", "acoustic"] },
  "soulful electronic music" : { "dance" : true, "R&B" : ["soul"], "electronic" : true },
  "soulful house" : { "dance" : true, "R&B" : ["soul"], "electronic" : ["house"] },
  "soulful progressive" : { "dance" : true, "R&B" : ["soul"], "electronic" : true },
  "soulful techno" : { "dance" : true, "R&B" : ["soul"], "electronic" : ["techno"] },
  "soulfull" : { "dance" : true, "R&B" : ["soul"] },
  "speed metal tropical sound" : { "dance" : true, "rock" : ["metal"], "international" : ["tropical"] },
  "spoken word poetry" : { "dance" : true, "hip-hop" : ["rap"] },
  "stattbad" : { "international" : ["stattbad"] },
  "super house" : { "dance" : true, "electronic" : ["house"] },
  "swamp" : null,
  "swing" : { "dance" : ["swing"] },
  "tech" : { "dance" : true, "electronic" : ["techno"] },
  "tech house" : { "dance" : true, "electronic" : ["techno", "house"] },
  "tech techno" : { "dance" : true, "electronic" : ["techno"] },
  "tech trance" : { "dance" : true, "electronic" : ["techno", "trance"] },
  "tech-house" : { "dance" : true, "electronic" : ["techno", "house"] },
  "techhouse" : { "dance" : true, "electronic" : ["techno", "house"] },
  "technno" : { "dance" : true, "electronic" : ["techno"] },
  "techno" : { "dance" : true, "electronic" : ["techno"] },
  "techno house" : { "dance" : true, "electronic" : ["techno", "house"] },
  "techno minimal" : { "dance" : true, "electronic" : ["techno"] },
  "techno subgenres" : { "dance" : true, "electronic" : ["techno"] },
  "techo" : { "dance" : true, "electronic" : ["techno"] },
  "toolhouserock" : { "dance" : true, "electronic" : true },
  "traditional" : null,
  "trance" : { "dance" : true, "electronic" : ["trance"] },
  "trap" : { "dance" : true, "hip-hop" : ["trap"] },
  "tresor" : null,
  "tribal" : { "international" : ["tribal"] },
  "tribal house" : { "dance" : true, "electronic" : ["house"], "international" : ["tribal"] },
  "triphop" : { "dance" : true, "electronic" : ["trip"], "hip-hop" : true },
  "triphouse" : { "dance" : true, "electronic" : ["trip", "house"] },
  "tropical" : { "international" : ["tropical"] },
  "twerk" : null,
  "underground" : { "dance" : ["underground"] },
  "underground deep" : { "dance" : ["underground"], "electronic" : ["deep"] },
  "underground electronic music" : { "dance" : ["underground"], "electronic" : true },
  "underground house" : { "dance" : ["underground"], "electronic" : ["house"] },
  "urban" : { "dance" : true },
  "voodoo" : { "international" : ["voodoo"] }
}