#!/usr/bin/env node
'use strict';

const orientjs  = require('orientjs');
const fs        = require('fs');

const USER = process.env.ROOT_USERNAME;
const PWD  = process.env.ROOT_PASSWORD;
const DB   = 'bookya-test-1';

const server = orientjs({
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  username: USER,
  password: PWD
});

server.create({
  name: DB,
  type: 'graph',
  storage: 'plocal'
})
.then(function () {
  return server.use({
    name: DB,
    username: 'admin',
    password: 'admin'
  });
})
.then(function(database) {
  let createSql = fs.readFileSync(process.cwd() + '/script/schema.sql', 'utf8');
  let sqls      = createSql.split('\n');

  sqls = sqls.map(function(sql) {
    if (!sql || sql.indexOf('#') > -1 || sql.indexOf('BEGIN') > -1 || sql.indexOf('COMMIT')  > -1) {
      return Promise.resolve('ignore');
    }

    return database.exec(sql);
  });

  return Promise.all(sqls);
})
.then(process.exit.bind(process, 0))
.catch(function(err) {
  console.error(err);
  process.exit(1);
});
