'use strict';

// agency
// const config = {
// 	NAME: 0,
// 	CONTACT_PERSON: 1,
// 	EMAIL: 2,
// 	CONTACT_NUMBER: 3,
// 	BASED_IN: 4,
// 	GENRES: 5,
// 	BIO: 6,
// 	WEBSITE: 7,
// 	FACEBOOK_PAGE: 8,
// 	INSTAGRAM_ID: 9,
// 	TWITTER_ID: 10,
// 	SOUNDCLOUD_ID: 11,
// 	YOUTUBE_CHANNEL: 12
// };

// promoter
const config = {
	NAME: 0,
	PROFILE_PHOTO: 1,
	BASED_IN: 2,
	BIO: 3,
	GENRES: 4,
	WEBSITE: 5,
	FACEBOOK_PAGE: 6,
	INSTAGRAM_ID: 7,
	SOUNDCLOUD_ID: 8,
	TWITTER_ID: 9,
	YOUTUBE_CHANNEL: 10,
	EVENT_TYPE_LIST: 11,
	EVENT_LOCATION_LIST: 12,
	CONCEPT_LIST: 13,
	SIGNIFICANT_BOOKING_LIST: 14,
	CONTACT_PERSON: 15,
	EMAIL: 16,
	CONTACT_NUMBER: 17
};

module.exports = config;
